// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1C4Qv1zRvg3CuaT_I7YT-SjDRAPEMXzw',
    appId: '1:247810435501:web:984961325b6489ec209924',
    messagingSenderId: '247810435501',
    projectId: 'labexam-50257',
    authDomain: 'labexam-50257.firebaseapp.com',
    databaseURL: 'https://labexam-50257-default-rtdb.firebaseio.com',
    storageBucket: 'labexam-50257.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuhQQiN3VVHmtwzLhbUSHejLHmfMVKf1k',
    appId: '1:247810435501:android:00e3c4ee09343568209924',
    messagingSenderId: '247810435501',
    projectId: 'labexam-50257',
    databaseURL: 'https://labexam-50257-default-rtdb.firebaseio.com',
    storageBucket: 'labexam-50257.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdu80kzwPTxUWJLWyrK28DxrXpGL7RGtQ',
    appId: '1:247810435501:ios:8c9f5e4f3aa49cc3209924',
    messagingSenderId: '247810435501',
    projectId: 'labexam-50257',
    databaseURL: 'https://labexam-50257-default-rtdb.firebaseio.com',
    storageBucket: 'labexam-50257.firebasestorage.app',
    iosBundleId: 'com.example.firebaselab',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdu80kzwPTxUWJLWyrK28DxrXpGL7RGtQ',
    appId: '1:247810435501:ios:8c9f5e4f3aa49cc3209924',
    messagingSenderId: '247810435501',
    projectId: 'labexam-50257',
    databaseURL: 'https://labexam-50257-default-rtdb.firebaseio.com',
    storageBucket: 'labexam-50257.firebasestorage.app',
    iosBundleId: 'com.example.firebaselab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1C4Qv1zRvg3CuaT_I7YT-SjDRAPEMXzw',
    appId: '1:247810435501:web:878ca87753794769209924',
    messagingSenderId: '247810435501',
    projectId: 'labexam-50257',
    authDomain: 'labexam-50257.firebaseapp.com',
    databaseURL: 'https://labexam-50257-default-rtdb.firebaseio.com',
    storageBucket: 'labexam-50257.firebasestorage.app',
  );

}